export const ORA_DESC_V = ["superfluous","addicted","conformist","nefarious","sensible","untrained","romantic","unreasonable","skilled","neglectful","lively","forthright","idealistic","unsupportive","rational","coarse","foolish","cunning","delightful","miserly","inept","banal","logical","subtle","reputable","wicked","lazy","pessimistic","solemn","habitual","meek","helpful","unconcerned","generous","docile","cheery","pragmatic","serene","thoughtful","hopeless","pleasant","insensitive","titled","inexperienced","prying","oblivious","refined","indispensable","scholarly","conservative","uncouth","willful","indifferent","fickle","elderly","sinful","naive","privileged","glum","likable","lethargic","defiant","obnoxious","insightful","tactless","fanatic","plebeian","childish","pious","uneducated","inconsiderate","cultured","revolting","curious","touchy","needy","dignified","pushy","kind","corrupt","jovial","shrewd","liberal","compliant","destitute","conniving","careful","alluring","defective","optimistic","affluent","despondent","mindless","passionate","devoted","established","unseemly","dependable","righteous","confident"];
export const ORA_DESC_N = ["gypsy","witch","merchant","expert","commoner","judge","ranger","occultist","reverend","thug","drifter","journeyman","statesman","astrologer","duelist","jack-of-all-trades","aristocrat","preacher","artisan","rogue","missionary","outcast","mercenary","caretaker","hermit","orator","chieftain","pioneer","burglar","vicar","officer","explorer","warden","outlaw","adept","bum","sorcerer","laborer","master","ascendant","villager","magus","conscript","worker","actor","herald","highwayman","fortune-hunter","governor","scrapper","monk","homemaker","recluse","steward","polymath","magician","traveler","vagrant","apprentice","politician","mediator","crook","civilian","activist","hero","champion","cleric","slave","gunman","clairvoyant","patriarch","shopkeeper","crone","adventurer","soldier","entertainer","craftsman","scientist","ascetic","superior","performer","magister","serf","brute","inquisitor","lord","villain","professor","servant","charmer","globetrotter","sniper","courtier","priest","tradesman","hitman","wizard","beggar","tradesman","warrior"];
export const ORA_MOT_V = ["advise","obtain","attempt","spoil","oppress","interact","create","abduct","promote","conceive","blight","progress","distress","possess","record","embrace","contact","pursue","associate","prepare","shepherd","abuse","indulge","chronicle","fulfill","drive","review","aid","follow","advance","guard","conquer","hinder","plunder","construct","encourage","agonize","comprehend","administer","relate","take","discover","deter","acquire","damage","publicize","burden","advocate","implement","understand","collaborate","strive","complete","compel","join","assist","defile","produce","institute","account","work","accompany","offend","guide","learn","persecute","communicate","process","report","develop","steal","suggest","weaken","achieve","secure","inform","patronize","depress","determine","seek","manage","suppress","proclaim","operate","access","refine","compose","undermine","explain","discourage","attend","detect","execute","maintain","realize","convey","rob","establish","overthrow","support"];
export const ORA_MOT_N = ["wealth","hardship","affluence","resources","prosperity","poverty","opulence","deprivation","success","distress","contraband","music","literature","technology","alcohol","medicines","beauty","strength","intelligence","force","the wealthy","the populous","enemies","the public","religion","the poor","family","the elite","academia","the forsaken","the law","the government","the oppressed","friends","criminals","allies","secret societies","the world","military","the church","dreams","discretion","love","freedom","pain","faith","slavery","enlightenment","racism","sensuality","dissonance","peace","discrimination","disbelief","pleasure","hate","happiness","servitude","harmony","justice","gluttony","lust","envy","greed","laziness","wrath","pride","purity","moderation","vigilance","zeal","composure","charity","modesty","atrocities","cowardice","narcissism","compassion","valor","patience","advice","propaganda","science","knowledge","communications","lies","myths","riddles","stories","legends","industry","new religions","progress","animals","ghosts","magic","nature","old religions","expertise","spirits"];
export const ORA_BEAR = [
    ["intent","bargain","means","proposition","plan","compromise","agenda","arrangement","negotiation","plot"],
    ["madness","fear","accident","chaos","idiocy","illusion","turmoil","confusion","façade","bewilderment"],
    ["alliance","comfort","gratitude","shelter","happiness","support","promise","delight","aid","celebration"],
    ["death","capture","judgment","combat","surrender","rage","resentment","submission","injury","destruction"],
    ["questions","investigation","interest","demand","suspicion","request","curiosity","skepticism","command","petition"],
    ["report","effects","examination","records","account","news","history","telling","discourse","speech"],
    ["rumor","uncertainty","secrets","misdirection","whispers","lies","shadows","enigma","obscurity","conundrum"],
    ["reputation","doubt","bias","dislike","partiality","belief","view","discrimination","assessment","difference"]
];
export const ORA_FOCUS = ["current scene","parents","wealth","skills","campaign","allies","flaws","experience","community","current story","weapons","last story","history","relics","superiors","future action","last scene","antagonist","knowledge","treasure","family","previous scene","equipment","retainers","last action","fame","friends","contacts","rewards","recent scene","the character","power","enemy"];
export const ORA_FATE = ["foreshadowing","tying off","to conflict","costume change","key grip","to knowledge","framing","set change","upstaged","pattern change","limelit","entering the red","to endings","montage","enter stage left","cross-stitch","six degrees"];
export const ORA_RELAT = ["Loved","Friendly","Peaceful","Neutral","Distrustful","Hostile","Hated"];
export const ORA_MOOD = ["Withdrawn","Guarded","Cautious","Neutral","Sociable","Helpful","Forthcoming"];